config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do 
    unauthenticated do
      root "products#welcome", as: :unauthenticated_root
    end
  end

  root "products#landing"
  resources :products, only: [:index, :show] do
    get :search, on: :collection
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    get :landing, on: :collection
    get :welcome, on: :collection
  end

  resource :users, only: :show do
    get :edit_member, on: :collection
    get :confirm_password, on: :collection
    post :update_member, on: :collection
    post :confirm, on: :collection
  end

  resource :cart do
    get :order_detail, on: :collection
  end

  post 'spgateway/return'
  post 'spgateway/notify'

  resources :orders do 
    post :checkout_spgateway, on: :member
    get :select_payment, on: :collection
    get :create_order, on: :collection
  end

  resources :categories, only: :show do
    get :man, on: :collection
    get :woman, on: :collection
    get :kid, on: :collection
    get :baby, on: :collection
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :ajion2596dhi do
    root "items#index"
    resources :users
    resources :orders
    resources :items do
      get :edit_detail, on: :member
      get :new_man, on: :collection
      get :new_woman, on: :collection
      get :new_kid, on: :collection
      get :new_baby, on: :collection

      resources :products
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates_presence_of :name, :minimum => 2

  has_many :orders

  def admin?
    self.role == "admin"
  end

  def self.from_fb_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      user.password = Devise.friendly_token[0,20]
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.name = auth.info.name
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.save!
    return user
  end

  def self.from_google_omniauth(auth)
    # Case 1: Find existing user by google uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.google_token = auth.credentials.token
      user.password = Devise.friendly_token[0,20]
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.google_uid = auth.uid
      existing_user.google_token = auth.credentials.token
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.name = auth.info.name
    user.google_uid = auth.uid
    user.google_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.save!
    return user
  end
  
end

app/controllers/ajion2596dhi/users_controller.rb
class Ajion2596dhi::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all.order("id DESC")
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "success"
      redirect_to ajion2596dhi_users_path
    else
      flash.now[:alert] = "failed"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to ajion2596dhi_users_path
    flash[:alert] = "user was deleted"
  end

  private 

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :role, :confirmed_at)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)

    super(resource_name, resource)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_fb_omniauth(request.env["omniauth.auth"])
 
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_google_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, alert: "fail"
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_up_params
      resource.validate # Look for any other validation errors besides Recaptcha
      set_minimum_password_length
      respond_with resource
    end 
  end
    
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :confirm_process, only: :edit_member

  def confirm_password
    @user = current_user
  end

  def confirm
    @user = current_user

    if @user.valid_password?(password_params.values.first)
      flash[:notice] = "success"
      confirm_process(false)
    else
      flash.now[:alert] = "輸入錯誤，請再輸入一次"
      render :confirm_password
    end
  end

  def edit_member
    @user = current_user
  end

  def update_member
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "success"
      redirect_to root_path
    else
      flash.now[:alert] = "failed"
      render :update_member
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
  end

  private 

  def user_params
    params.require(:user).permit(:name, :address, :phone, :tax_id)
  end

  def password_params
    params.require(:user).permit(:password)
  end

  def confirm_process(result = true)
    if result
      redirect_to confirm_password_users_url
    else
      render :edit_member
    end
  end
end

app/helpers/ajion2596dhi/users_helper.rb
module Ajion2596dhi::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm_password.html.erb
<% tab "member" %>
<div class="bg-box">

  <div class="member-set">
    <%= link_to orders_path, :class => 'member-link' do %>
      訂單查詢
    <% end %>

    <%= link_to users_path, {:class => 'member-link underline', :style => 'float: right;'} do %>
      帳號設定
    <% end %>
  </div>

  <div class="login">

    <div style="margin: 60px 0px;font-size: 13px;">
      個人資料安全認證<br><br><br>為了保障你的資料安全，必須再次填入密碼驗證。
    </div>

    <%= form_for(@user, url: confirm_users_path, html: { method: :post }) do |f| %>

      <div class="field" style="margin-bottom:60px">
        密碼
        <%= f.password_field :password, autocomplete: "off", style: "margin-left:40px", class: "form-style" %>
      </div>

      <div class="actions submit-button" style="margin-bottom: 10px; text-align: center;">
        <%= f.submit "送出", style: "width: 50%;background-color: #59544f;margin-bottom: 20px",class: "login-submit" %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/edit_member.html.erb
<% tab "member" %>
<div class="bg-box">

  <div class="member-set">
    <%= link_to orders_path, :class => 'member-link' do %>
      訂單查詢
    <% end %>

    <%= link_to users_path, {:class => 'member-link underline', :style => 'float: right;'} do %>
      帳號設定
    <% end %>
  </div>

  <div class="login" style="text-align: center; margin-top: 40px;">
    
    <%= form_for(@user, url: update_member_users_path, html: { method: :post }) do |f| %>

      <div style="text-align: left; padding-left: 20%;">
        <div class="field" style="margin-bottom:40px;">
          <span>信箱</span>
          <span class="form-style box" style="margin-left: 70px;"><%= @user.email %></span>
        </div>

        <div class="field" style="margin-bottom:40px;">
          聯絡人
          <%= f.text_field :name, autofocus: true, style: "margin-left:55px",  class: "form-style box" %>
        </div>

        <div class="field" style="margin-bottom:40px;">
          連絡電話
          <%= f.text_field :phone, style: "margin-left:40px",  class: "form-style box" %>
        </div>

        <div class="field" style="margin-bottom:40px;">
          聯絡地址
          <%= f.text_field :address, style: "margin-left:40px",  class: "form-style box" %>
        </div>

        <div class="field" style="margin-bottom:40px;">
          統一編號
          <%= f.text_field :tax_id, style: "margin-left:40px",  class: "form-style box" %>
        </div>
      </div>

      <div class="actions submit-button" style="margin-bottom: 10px; text-align: center;">
        <%= f.submit "確認修改", style: "width: 50%;background-color: #59544f;margin: 20px 0px",class: "login-submit" %>
      </div>

    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<% tab "member" %>
<div class="bg-box">

  <div class="member-set">
    <%= link_to orders_path, :class => 'member-link' do %>
      訂單查詢
    <% end %>

    <%= link_to users_path, {:class => 'member-link underline', :style => 'float: right;'} do %>
      帳號設定
    <% end %>
  </div>

  <div style="text-align: center; margin: 40px 0px;">
    <%= link_to edit_member_users_path do %>
      <button class="member-btn" style="background-color: #59544f">修改資料</button> <br>
    <% end %>

    <%= link_to edit_user_registration_path do %>
      <button class="member-btn"  style="background-color: #5f0ac7">修改密碼</button> <br>
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete do %>
      <button class="member-btn"  style="background-color: #c1c0bc">會員登出</button> <br>
    <% end %>
  </div>

</div>