config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do 
    unauthenticated do
      root "products#welcome", as: :unauthenticated_root
    end
  end

  root "products#landing"
  resources :products, only: [:index, :show] do
    get :search, on: :collection
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    get :landing, on: :collection
    get :welcome, on: :collection
  end

  resource :users, only: :show do
    get :edit_member, on: :collection
    get :confirm_password, on: :collection
    post :update_member, on: :collection
    post :confirm, on: :collection
  end

  resource :cart do
    get :order_detail, on: :collection
  end

  post 'spgateway/return'
  post 'spgateway/notify'

  resources :orders do 
    post :checkout_spgateway, on: :member
    get :select_payment, on: :collection
    get :create_order, on: :collection
  end

  resources :categories, only: :show do
    get :man, on: :collection
    get :woman, on: :collection
    get :kid, on: :collection
    get :baby, on: :collection
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :ajion2596dhi do
    root "items#index"
    resources :users
    resources :orders
    resources :items do
      get :edit_detail, on: :member
      get :new_man, on: :collection
      get :new_woman, on: :collection
      get :new_kid, on: :collection
      get :new_baby, on: :collection

      resources :products
    end
  end
end

app/views/shared/_category.html.erb
<div class="col-sm-2">
  <br>
  <% @where.each do |where| %>
    <%= where %><br>
    <% @categories.where(where: where).each do |c| %>
      <%= link_to c.name, category_path(c), class:'link', style: 'color: #848378;' %>
      <br>
    <% end %>
    <br><br>
  <% end %>
</div>

<style type="text/css">
  body {
    background-color: white;
    background-image: none;
  }
</style>

app/views/shared/_product.html.erb
<div class="col-sm-10 col-sx-12" style="padding-top: 20px">
  <% @products.each do |product| %>
    <div class="col-sm-3 col-xs-6" style="padding-left: 7px; padding-right: 7px">

      <div id=<%= product.id %> class="add-cart-show">
        
        <div class="clearfix">
          <div class="color-list" style= "float:left">
            <p style="margin-top: 18px; margin-left: 15px;">顏色</p>
            <div style="margin-left: 10px; width: 160px">
              <% @firstColor = product.products.pluck(:color).first %>
              <% product.products.pluck(:color).uniq.each do |color| %>
                <div id=<%= color %> class="colorbox" style="background-color: #<%= color %>; margin-top: 5px; float: left; margin-left: 5px;"></div>
              <% end %>
            </div>
          </div> 

          <div class="size-list" style="width: 150px; margin-left: 10px; float: left">
            <p style="margin-top: 18px;">尺寸</p>
            <div style="margin-top: 5px;">
              <% product.products.where(color: @firstColor).pluck(:size).uniq.each do |color| %>
                <div class="sizebox"><%= color %></div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="clearfix">
          <div style= "float:left">
            <p style="margin-top: 18px; margin-left: 15px;">數量</p>
            <div style="margin-left: 10px; margin-top: 5px; width: 160px">
              <input type='button' value='-' style="font-size:15px; color: #848378;" id='minus' class='qtyminus'/>

              <input type='text' value=1 style='color:#59544f;' id='number' class='qty' />

              <input type='button' value='+' style="color: #848378;" id='plus' class='qtyplus'/>
            </div>
          </div> 

          <div style="width: 150px; margin-left: 10px; float: left; margin-top: 18px;">
            <span>庫存量：</span>
            <sapn class="stock"><%= product.products.first.stock %></sapn>
            <div class="add-cart-btn"><p>加入購物車</p></div>
          </div>
        </div>

        <div class="trangle-before"></div>
        <div class="trangle-after"></div>
      </div>

      <%= link_to product_path(product) do %>
        <%= image_tag product.main_image, width: "100%" %>
      <% end %>
      <div class="add-cart">
        加入購物車
      </div>
      
      <div style="padding-left: 2px; margint-top: 5px">
        <%= link_to product_path(product), class: 'link' do %>
          <%= product.name %><br>
          <hr style="border-color: white; margin: 3px 0px;">
          $<%= product.price %><br>
        <% end %>
      </div>

      <br>
    </div>
  <% end %>
  <div id="success"><p>加入購物車成功！</p></div>
</div>

<script type="text/javascript">
  var color = "none";
  var size = "none";
  var min = 1;

  $(document).on('click', function(e) {
    if($(e.target).closest('.add-cart').length){
      $('.add-cart-show').hide();
      $(e.target).prevAll().show();
      color = $(e.target).prevAll().find(".colorbox:first-of-type").attr("id");
      size = $(e.target).prevAll().find(".sizebox:first-of-type").text();
    }else if($('.add-cart-show:visible').closest('.add-cart-show').length){
      if(!$(e.target).closest('.add-cart-show').length){
        $('.add-cart-show').hide();
        $('.colorbox').css("outline", "none");
        $('.colorbox:first-of-type').css("outline", "1px solid black");
        $('.sizebox').css("outline", "none");
        $('.sizebox:first-of-type').css("outline", "1px solid black");
      }
    }
  });

  $(".add-cart-btn").click(function(){
    $.ajax({
      url: '/products/' + $(this).parent().parent().parent().attr('id') + '/add_to_cart',
      method: 'POST',
      dataType: "text",
      data:{
        color: color,
        size: size,
        quantity: parseInt($(this).parent().prevAll().find('input.qty').val())
      }
    });

    $("#success").fadeIn(500);
    $('.add-cart-show').hide();
    $("#success").fadeOut(500);
  })

  $(".colorbox").click(function(){
    $(this).parent().find(".colorbox").css("outline", "none");
    $(this).css("outline", "1px solid black");
    color = $(this).attr('id');
  })

  $(".sizebox").click(function(){
    $(this).parent().find(".sizebox").css("outline", "none");
    $(this).css("outline", "1px solid black");
    size = $(this).text();
  })

  $('.qtyplus').click(function(e) {
    var currentVal = parseInt($(this).prev('input').val());
    var max = parseInt($(this).parent().parent().next().children(".stock").text());
    if (currentVal < max) {
      $(this).prev('input').val(currentVal + 1);
    } else {
      $(this).prev('input').val(max);
    }
  });
  
  $(".qtyminus").click(function(e) {
    var currentVal = parseInt($(this).next('input').val());
    if (currentVal > min) {
      $(this).next('input').val(currentVal - 1);
    } else {
      $(this).next('input').val(min);
    }
  });

  $(".qty").blur(function(e){
    var currentVal = parseInt($(this).closest('input').val());
    var max = parseInt($(this).parent().parent().next().children(".stock").text());
    if (currentVal < min || isNaN(currentVal)) {
      $(this).val(min);
    } else if(currentVal > max) {
      $(this).val(max);
    }
  });
</script>

<style type="text/css">
  .add-cart {
    margin-bottom: 10px;
    width: 100%;
    background-color: #c893fa;
    font-size: 14px;
    color: #ffffff;
    line-height: 35px;
    text-align: center;
    cursor: pointer;
  }

  .add-cart-show {
    right: -50px;
    bottom: 140px;
    position: absolute;
    width: 335px;
    height: 180px;
    background-color: #ffffff;
    font-size: 16px;
    color: #59544f;
    border: 0.1px solid;
    border-color: #c1c0bc;
    opacity: 0.95;
    z-index: 1;
    display: none;
  }

  .trangle-before {
    position: absolute;
    bottom: -39px;
    border-style: solid;
    border-color: transparent;
    border-top-color: white;
    border-width: 20px;
    left: 49%;
    margin-left: -21px;
    z-index: 20;
  }

  .trangle-after {
    position: absolute;
    bottom: -40px;
    border-style: solid;
    border-color: transparent;
    border-top-color: #59544f;
    border-width: 20px;
    left: 49%;
    margin-left: -21px;
    opacity: 0.9;
  }

  .colorbox {
    border: 1px solid white;
    height: 25px;
    width: 25px;
    padding: 2px;
    cursor: pointer;
  }

  .colorbox:first-of-type, .sizebox:first-of-type {
    outline: 1px solid black;
  }

  .sizebox {
    float: left;
    width: 28px;
    height: 25px;
    background-color: #eee;
    margin-right: 5px;
    text-align: center;
    line-height: 25px;
    border: 1px solid white;
    cursor: pointer;
  }

  .qty {
    top: 2px;
    left: 5px;
    width: 80px;
  }

  .qtyminus, .qtyplus {
    top: 2px;
    left: 5px;
  }

  .add-cart-btn {
    margin-top: 5px;
    background-color: #9b3af6;
    color: white;
    text-align: center;
    width: 120px;
    height: 25px;
    line-height: 25px;
    font-size: 14px;
    cursor: pointer;
  }

  #success {
    position: fixed;
    top: 45%;
    left: 45%;
    width: 250px;
    height: 65px;
    background-color: white;
    opacity: 0.85;
    color: #59544f;
    line-height: 65px;
    text-align: center;
    display: none;
  }
</style>