config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do 
    unauthenticated do
      root "products#welcome", as: :unauthenticated_root
    end
  end

  root "products#landing"
  resources :products, only: [:index, :show] do
    get :search, on: :collection
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    get :landing, on: :collection
    get :welcome, on: :collection
  end

  resource :users, only: :show do
    get :edit_member, on: :collection
    get :confirm_password, on: :collection
    post :update_member, on: :collection
    post :confirm, on: :collection
  end

  resource :cart do
    get :order_detail, on: :collection
  end

  post 'spgateway/return'
  post 'spgateway/notify'

  resources :orders do 
    post :checkout_spgateway, on: :member
    get :select_payment, on: :collection
    get :create_order, on: :collection
  end

  resources :categories, only: :show do
    get :man, on: :collection
    get :woman, on: :collection
    get :kid, on: :collection
    get :baby, on: :collection
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :ajion2596dhi do
    root "items#index"
    resources :users
    resources :orders
    resources :items do
      get :edit_detail, on: :member
      get :new_man, on: :collection
      get :new_woman, on: :collection
      get :new_kid, on: :collection
      get :new_baby, on: :collection

      resources :products
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :user

  def add_cart_item(product, quantity)
    existing_item = self.cart_items.find_by(product: product)
    if existing_item
      existing_item.quantity += quantity
      existing_item.save!
    else
      cart_item = cart_items.build(product: product, quantity: quantity)
      cart_item.save!
    end
    self.cart_items
  end

  def subtotal
    cart_items.map{ |x| x.item_total }.sum
  end

  def find_item_by(product)
    self.cart_item.where(product_id: product).first
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_cart
    @items = current_cart.cart_items
  end

  def order_detail
    @user = current_user
    @order = Order.new
    @items = current_cart.cart_items
    @total = 0
    @items.each do |i|
      @total = @total + i.quantity * i.product.item.price
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/order_detail.html.erb
<% tab "cart" %>

<div class="bg-box">
  <div class="only-mobile cart-banner">
    <span style="color: #ffffff;">付款方式</span>
  </div>

  <div class="mobile-none" style="">
    <%= image_tag "step-2.png", style: "width: 90%; margin-left: 5%; margin-bottom: 30px"%>
  </div>
  
  <div style="margin: 10px 30px;">
    <div style="margin-left: 20px; margin-right: 20px">
      <%= form_for(@order) do |f| %>

        <div class="field" style="margin-bottom: 20px;">
          信箱
          <span style="margin-left: 30px"><%= @user.email%></span>  
        </div>

        <div class="field" style="margin-bottom: 20px;">
          <span style="color: red; margin-left: -8px">*</span>
          聯絡人
          <%= f.text_field :name, style: "margin-left:14px; width: 35%", class: "form-style"%>
        </div>

        <div class="field" style="margin-bottom: 20px; float: left; margin-right: 15px">
          市話
          <%= f.text_field :telephone, style: "margin-left:25px; width: 35px", class: "form-style" %>-
          <%= f.text_field :telephone_2, style: "width: 70px", class: "form-style" %>-
          <%= f.text_field :telephone_3, style: "width: 50px;", class: "form-style" %>
        </div>

        <div class="field" style="margin-bottom: 20px;">
          <span style="color: red; margin-left: -8px">*</span>
          手機
          <%= f.text_field :phone, style: "margin-left:25px; width: 34%; margin-right: -20px", class: "form-style" %>
        </div>

        <div class="field" style="margin-bottom: 20px;">
          <span style="color: red; margin-left: -8px">*</span>
          地址
          <div id="twzipcode", class: "form-style" style="margin-left: -10px;float: right"></div>
          <%= f.text_field :address, placeholder: "請輸入地址",style: "width: 100%;margin-left:30px; margin-left: -5px", class: "form-style" %>
        </div>

        <div class="field" style="margin-bottom: 20px;">
          統一編號
          <%= f.text_field :tax_id, style: "margin-left:1px; width: 35%", class: "form-style" %>
        </div>
      

        <hr style="margin-top: 40px; margin-left: -20px; margin-right: -20px;">

        <div class="clearfix" style=" margin-left: -20px; margin-right: -20px;">
          <div style="position: relative; margin-top: 10px; float: right;">

            <span>共&nbsp;<%= @items.pluck(:quantity).inject(:+) %>&nbsp;件商品</span> &nbsp;&nbsp;&nbsp;&nbsp;
            <span>商品金額&nbsp;&nbsp;&nbsp;&nbsp;$ <%= @total %></span>  

          </div>
        </div>

        <div class="clearfix" style="margin-top: 60px;margin-left: -50px; margin-bottom: 10px; margin-right: -20px">

          <%= link_to cart_path do %>
            <button class="cart-button" style="float: left">←&nbsp;上一步</button>
          <% end %>
          
          <div style="float: right" data-turbolinks="false">
            <%= f.submit "成立訂單", class: "order-submit" %>
          </div>
          
        </div>
        
      </div>
      
    <% end %>
  </div> 
  
</div>

<script type="text/javascript">
  $('#twzipcode').twzipcode({
      'css': ['county', 'district', 'zipcode']
  });
</script>

app/views/carts/show.html.erb
<% tab "cart" %>

<div class="bg-box">
  <div class="only-mobile cart-banner">
    <span style="color: #ffffff;">購物車</span>
  </div>

  <div class="mobile-none" style="">
    <%= image_tag "step-1.png", style: "width: 90%; margin-left: 5%; margin-bottom: 15px"%>
  </div>
  
  <% if @items.empty? %>

    <div style="height: 280px; display: flex; align-items: center; justify-content: center;">
      <%= image_tag "cart-null.png", style: "height: 40%;"%>
    </div>

    <div style="text-align: center; margin-top: -10%; margin-bottom: 40px;">
      <span>您的購物車沒有商品</span><br>
      <%= link_to root_path do %>
        <button class="member-btn" style="background-color: #59544f; margin: 20px 0px; width: 120px;">去購物</button>
      <% end %>
    </div>

  <% else %>
    <% total = 0 %>
    <% @items.each do |item| %>
      <div style="margin: 10px 30px; border: 0.1px solid; border-color: #c1c0bc; line-height: 18px; height: 122px;">

        <%= link_to remove_from_cart_product_path(item.product), method: :post, remote: true do %>
          <button style="margin: 10px 10px;" type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>

        <%= image_tag item.product.item.main_image, width: "80px", style: "margin: 8px 15px;" %>

        <div class="cart-item" id=<%= item.product.id %> style="margin-left: 110px; margin-top: -110px; margin-bottom: -80px;">
          <div>
              <%= item.product.item.name %><br><br>

              <div style="margin-top: 6px; margin-bottom: 6px">
                尺寸&nbsp;&nbsp;<%= item.product.size %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;顏色&nbsp;
                <div class="colorbox" style="position: relative; top: -16px; left: 108px; background-color: #<%= item.product.color %>;"></div>
              </div>

              <span>單價&nbsp;&nbsp;$</span>
              <span class="item-price"><%= item.product.item.price %></span>  
          </div>

          <div id=<%= item.product.stock %> >
            
            <%= link_to adjust_item_product_path(item.product, type: "substract"), method: :post, remote: true do %>
              <input type='button' value='-' style="font-size:15px; color: #848378;" id='minus' class='qtyminus'/>
            <% end %>

            <input type='text' value=<%= item.quantity %> style='color:#59544f;' id='number' class='qty' />

            <%= link_to  adjust_item_product_path(item.product, type: "add"), method: :post, remote: true  do %>
              <input type='button' value='+' style="color: #848378;" id='plus' class='qtyplus'/>
            <% end %>

          </div>
          
          <div style="margin-top: -75px; margin-left: 280px">
            <span>$&nbsp;</span>
            <span class="item-total-price"><%= item.product.item.price * item.quantity %></span>
          </div>

        </div>

      </div>
      <% total = total + item.product.item.price * item.quantity %>
    <% end %>
    
    <div class="clearfix">
      <div style="position: relative; margin-top: 20px; margin-right: 30px; float: right;">

        <span>共&nbsp;</span>
        <span class="total-quantity"><%= @items.pluck(:quantity).inject(:+) %></span>
        <span>&nbsp;件商品 &nbsp;&nbsp;&nbsp;&nbsp;商品金額&nbsp;&nbsp;&nbsp;&nbsp;$ </span>
        <span class="total-price"><%= total %></span>  

      </div>
    </div>

    <div class="clearfix" style="margin-top: 60px;margin-right: 30px; margin-bottom: 10px">

      <%= link_to root_path do %>
        <button class="cart-button" style="float: left">←&nbsp;繼續購物</button>
      <% end %>

      <%= link_to order_detail_cart_path do %>
        <button class="cart-button" style="float: right; background-color: #9b3af6; color: #ffffff">結帳</button>
      <% end %>
      
    </div>

  <% end %>
</div>

<script type="text/javascript">
  var min = 1
  var total_price = 0
  var total_quantity = 0

  $('.qtyplus').click(function(e) {
    var currentVal = parseInt($(this).parent().prev('input').val());
    var max = parseInt($(this).closest('div').attr('id'));
    if (currentVal < max) {
      $(this).parent().prev('input').val(currentVal + 1);
      $(this).parent().parent().next().children('.item-total-price').text(parseInt($(this).parent().parent().prev().children('.item-price').text())*(currentVal+1));
    } else {
      $(this).parent().prev('input').val(max);
    }

    total_price = 0
    total_quantity = 0
    $(".item-total-price:visible").each(function() {
      total_price += parseInt($(this).text());
    });
    $(".qty:visible").each(function() {
        total_quantity += parseInt($(this).val());
    });

    $('.total-price').text(total_price);
    $('.total-quantity').text(total_quantity);
  });
  
  $(".qtyminus").click(function(e) {
    var currentVal = parseInt($(this).parent().next('input').val());
    var max = parseInt($(this).closest('div').attr('id'));
    if (currentVal > min) {
      $(this).parent().next('input').val(currentVal - 1);
      $(this).parent().parent().next().children('.item-total-price').text(parseInt($(this).parent().parent().prev().children('.item-price').text())*(currentVal-1));
    } else {
      $(this).parent().next('input').val(min);
    }

    total_price = 0
    total_quantity = 0
    $(".item-total-price:visible").each(function() {
      total_price += parseInt($(this).text());
    });
    $(".qty:visible").each(function() {
        total_quantity += parseInt($(this).val());
    });

    $('.total-price').text(total_price);
    $('.total-quantity').text(total_quantity);
  });

  $(".qty").blur(function(e){
    var currentVal = parseInt($(this).closest('input').val());
    var max = parseInt($(this).closest('div').attr('id'));
    if (currentVal < min || isNaN(currentVal)) {
      $(this).val(min);
      $(this).parent().next().children('.item-total-price').text(parseInt($(this).parent().prev().children('.item-price').text())*min);
    } else if(currentVal > max) {
      $(this).val(max);
      $(this).parent().next().children('.item-total-price').text(parseInt($(this).parent().prev().children('.item-price').text())*max);
    } else {
      $(this).parent().next().children('.item-total-price').text(parseInt($(this).parent().prev().children('.item-price').text())*currentVal);
    }

    total_price = 0
    total_quantity = 0
    $(".item-total-price:visible").each(function() {
      total_price += parseInt($(this).text());
    });
    $(".qty:visible").each(function() {
        total_quantity += parseInt($(this).val());
    });

    $('.total-price').text(total_price);
    $('.total-quantity').text(total_quantity);

    $.ajax({
      url: '/products/' + $(this).parent().parent().attr('id') + '/adjust_item',
      method: 'POST',
      dataType: "text",
      data:{
        number: parseInt($(this).closest('input').val())
      }
    });
  });
  
  $(".close").click(function(){
    if($('.cart-item:visible').length - 1 == 0){
      window.location.reload(false); 
    }
    $(this).closest('div').hide();

    total_price = 0
    total_quantity = 0
    $(".item-total-price:visible").each(function() {
      total_price += parseInt($(this).text());
    });
    $(".qty:visible").each(function() {
        total_quantity += parseInt($(this).val());
    });

    $('.total-price').text(total_price);
    $('.total-quantity').text(total_quantity);
  })
  
</script>