config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do 
    unauthenticated do
      root "products#welcome", as: :unauthenticated_root
    end
  end

  root "products#landing"
  resources :products, only: [:index, :show] do
    get :search, on: :collection
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    get :landing, on: :collection
    get :welcome, on: :collection
  end

  resource :users, only: :show do
    get :edit_member, on: :collection
    get :confirm_password, on: :collection
    post :update_member, on: :collection
    post :confirm, on: :collection
  end

  resource :cart do
    get :order_detail, on: :collection
  end

  post 'spgateway/return'
  post 'spgateway/notify'

  resources :orders do 
    post :checkout_spgateway, on: :member
    get :select_payment, on: :collection
    get :create_order, on: :collection
  end

  resources :categories, only: :show do
    get :man, on: :collection
    get :woman, on: :collection
    get :kid, on: :collection
    get :baby, on: :collection
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :ajion2596dhi do
    root "items#index"
    resources :users
    resources :orders
    resources :items do
      get :edit_detail, on: :member
      get :new_man, on: :collection
      get :new_woman, on: :collection
      get :new_kid, on: :collection
      get :new_baby, on: :collection

      resources :products
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :color, :size, :stock

  mount_uploader :image, ImageUploader

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

  belongs_to :item
end

app/controllers/ajion2596dhi/products_controller.rb
class Ajion2596dhi::ProductsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    @product = Product.new(product_params)
    @product.item_id = item.id
    @product.save!
    redirect_to ajion2596dhi_item_path(item) 
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to ajion2596dhi_item_path(@product.item)
    flash[:alert] = "product was deleted"
  end

  private

  def product_params
    params.require(:product).permit(:size, :color, :image, :stock, :item_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: :search
  before_action :authenticate_user!, except: :welcome

  def welcome

  end

  def add_to_cart
    @item = Item.find(params[:id])
    @product = @item.products.where(color: params[:color], size: params[:size]).first
    current_cart.add_cart_item(@product, params[:quantity])

    #redirect_back(fallback_location: root_path)
  end

  def remove_from_cart
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    cart_item.destroy
    #redirect_back(fallback_location: root_path)
  end

  def adjust_item
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    if params[:type] == "add"
      if cart_item.quantity < @product.stock.to_i
        cart_item.quantity += 1
      end
    elsif params[:type] == "substract"
      cart_item.quantity -= 1
    elsif !params[:number].nil?
      cart_item.quantity = params[:number]
    end

    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save
    end
    # redirect_back(fallback_location: root_path)
  end

  def search_size
    @product = Product.find(params[:id])
    @size = @product.products.where(color: params[:color]).pluck(:size).uniq
  end

  def index
    @products = ProductItem.all
  end

  def landing
    gon.title = Scrape.last(22).pluck(:title)
    gon.size = Scrape.last(22).pluck(:size)
  end

  def search
    if @query_string.present?
     @products = Item.ransack(name_cont_any: [@query_string]).result
    end
  end

  protected

  def validate_search_key
    @query_string = params[:search].gsub(/\\|\'|\/|\?/, "") if params[:search].present?
  end

end

app/helpers/ajion2596dhi/products_helper.rb
module Ajion2596dhi::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <br>
    
    <% @products.each do |product| %>
      <div class="col-sm-3">
        <%= image_tag product.main_image, width: "150px" %><br>
        <%= product.name %><br>
        $<%= product.price %><br>
        <%= link_to "Add to Cart", add_to_cart_product_path(product), method: :post, class: "btn btn-info" %>
        <br><br>
      </div>
    <% end %>

  </div>
</div>

app/views/products/landing.html.erb
<% tab "index" %>

<div class="container">
  <!--Carousel-->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="https://farm5.staticflickr.com/4866/44387161250_dbd465f098_k.jpg alt="..." style="width:100%;">
      </div>

      <div class="item">
        <img src="https://farm5.staticflickr.com/4896/44387157540_229fda41a4_k.jpg" alt="..." style="width:100%;">
      </div>
    
      <div class="item">
        <img src="https://farm5.staticflickr.com/4813/32332219188_e502f2569c_k.jpg" alt="..." style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<br><br><br>

<div class="container">
  <div class="row">

    <div class="col-xs-4 col-md-4 col-sm-4 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4868/31265193967_a407b76b0a_k.jpg" alt="..." class="img-reponsive" width="100%">
    </div>

    <div class="col-xs-4 col-md-4 col-sm-4 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4891/31265191487_17604ab0cd_k.jpg" alt="..." class="img-reponsive" width="100%">
    </div>

    <div class="col-xs-4 col-md-4 col-sm-4 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4903/31265188657_5bff5f0eb3_k.jpg" alt="..." class="img-reponsive" width="100%">
    </div>

  </div>
</div>

<br><br><br>

<div class="container">
  <div class="row">

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4885/45291589815_cc94ea3dd2_k.jpg" alt="..." class="img-reponsive" width="100%">

      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4907/31265187207_9f5aeb21ca_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4879/45291584425_df70af663a_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4809/31265181027_abc96890cd_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4870/31265176697_c78bf7d30b_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4825/31265176067_b38089caad_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4804/44387133190_dd0a1438a0_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

    <div class="col-xs-6 col-md-3 col-sm-3 offset--xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4877/31265171937_e1b82f54cc_k.jpg" alt="..." class="img-reponsive" width="100%">
      
      <br>

      <br><br>
    </div>

  </div>
</div>

<br><br>

<div class="container"> 
  <div class="row">

    <div class="col-xs-12 col-md-12 col-sm-12 offset-xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4830/46153620142_f4159bb85e_k.jpg" alt="..." class="img-reponsive" width="100%">
      <br><br><br><br>
    </div>

    <div class="col-xs-12 col-md-12 col-sm-12 offset-xs-1 offset-md-1 offset-sm-1">
      <img src="https://farm5.staticflickr.com/4884/44387162300_060c83eb72_k.jpg" alt="..." class="img-reponsive" width="100%">
      <br><br><br><br>
    </div>

    <div class="col-xs-12 col-md-12 col-sm-12 offset-xs-1 offset-md-1 offset-sm-1">
      <div class="img-responsive" id="example" style="width: 100%; height: 450px; background-color: white; margin: 0px auto;"></div>
      <br><br><br><br>
    </div>

  </div>
</div>

<script type="text/javascript">
  
  var i = 0

  var words = [{text: '', weight: 0}]

  while(i < gon.title.length-1){
    if(gon.size[i] > 50){
      words.push({ text: gon.title[i], weight: gon.size[i] - i * 3})
    }else{
      words.push({ text: gon.title[i], weight: gon.size[i]})
    }
    i += 1
  }
  
  $("#example").jQCloud(words);
  $("#example").css("font-family", "微軟正黑體");

</script>

<style type="text/css">

.w4 {
  color: #B28FCE !important;
}

.w5 {
  color: #986DB2 !important;
}

.w6 {
  color: #77428D !important;
}

.w7 {
  color: #66327C !important;
}

.w8 {
  color: #533D58 !important;
}

.w9 {
  color: #4A225D !important;
}

.w10 {
  color: #3C2F41 !important;
}

</style>

app/views/products/search.html.erb
<div class="bg-box">
  <div>

    <%= link_to request.referer.present? ? request.referer : default_pat do %>
      <button class="cart-button" style="margin-left: 420px">回到上一頁</button>
    <% end %>

  </div>
  
  <% @products.each do |item| %>
    <%= link_to product_path(item) do %>
      <div style="margin: 10px 30px; border: 0.1px solid; border-color: #c1c0bc; line-height: 18px; height: 122px;color: black">

        <%= image_tag item.main_image, width: "80px", style: "margin: 8px 15px;" %>

        <div style="margin-left: 110px; margin-top: -110px; margin-bottom: -80px;">
          <div>
              <%= item.name %><br><br>

              單價&nbsp;&nbsp;$<%= item.price %><br><br>

              <%= item.intro %>
          </div>

        </div>

      </div>
    <% end %>
  <% end %>

  <div style="margin-top: 60px;">

    <%= link_to request.referer.present? ? request.referer : default_pat do %>
      <button class="cart-button" style="margin-left: 420px">回到上一頁</button>
    <% end %>

  </div>

</div>

app/views/products/welcome.html.erb
<style>
  body, html {
    height: 100%;
    margin: 0;
  }

  svg {
    width: 100%;
    height: 100%;
    margin-top: -5px;
  }

  svg > text {
    font-family: 'Noto Sans TC', sans-serif !important;
  }

  .welcome-button {
    text-align: center;
    
  }

  .button {
    margin-top: 5%;
    margin-bottom: 8%;
    color: white;
    background-color: #5f0ac7;
    font-size: 24px;
    font-weight: bold;
    width: 200px;
    height: 55px;
    outline: none;
    text-transform: none;
    border-radius: 30px;
    border: none;
    letter-spacing: 5px;
  }

</style>

<body>
    <div>
        <%= render partial: "shared/firstimage" %>
    </div>
    <div style="background-color: white; margin-top: -5px">
        <br>
    </div>
    <div>
        <%= render partial: "shared/welcomeimage" %>
    </div>
    <div class="welcome-button">
        <%= link_to new_user_registration_path do %>
            <button class="button">立即註冊</button>
        <% end %>
    </div>
</body>